fix(windows): Intermittent crash on `Luv.Process.spawn`
aantron/luv pull request #87
Opened 2020-12-01 18:11 UTC by bryphe

This is a fix for an intermittent crash occurring when calling `Luv.Process.spawn`.

This crash was observed while working on Onivim 2 on Windows - when running with `esy run -f`, the process would crash fairly reliably (~80%) at `Luv.Process.spawn`. Interestingly, this _did not_ reproduce when disabling logging, or when logging with `--trace` - this led me to suspect a GC integration issue (the differing log levels change the pattern of allocations, so if there is a crash in a particular log level, it's likely that a particular allocation pattern is getting us to that crash...)

Using `fprintf`s, I could confirm that the crash occurred during the call to `uv_spawn` here: https://github.com/aantron/luv/blob/59a5418145bc6af3570ec5341d108f8df4e4da35/src/c/helpers.c#L648

Upon experimenting - it seems that there is no guarantee that the strings or string arrays passed are 'pinned' in memory - the GC could, potentially, move the values around when the runtime system is released, and I believe this is the case I was hitting with `esy run -f` - it happened to be the compaction happened in a way to shuffle the strings around. Both the `CArray` and string pointers seem to be to OCaml-managed strings (ie, given by `String_val`)

According the [FFI docs](https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html) here:
```
After caml_release_runtime_system() was called and until caml_acquire_runtime_system() is called, the C code must not access any OCaml data, nor call any function of the run-time system, nor call back into OCaml code. Consequently, arguments provided by OCaml to the C primitive must be copied into C data structures before calling caml_release_runtime_system(), and results to be returned to OCaml must be encoded as OCaml values after caml_acquire_runtime_system() returns.
```
we should be making sure we aren't accessing OCaml-managed values when the runtime system is released, and I believe we are in this case. It might be there's a different type to use for ctypes to handle this (`string` vs `ocaml_string`) - but I'm not an expert in ctypes, so perhaps there is a cleaner fix.

This proposed change allocates C-managed memory for `cwd`, `file_path`, `args`, and `env`, and uses the c-managed memory, which won't be pulled out from underneath us like the OCaml-managed memory could be. Once the process is spawned, we can free that memory.

2020-12-02 02:14 UTC, bryphe commented
With this change - I'm still getting an ASAN error in some cases:
```
==23176==ERROR: AddressSanitizer: heap-use-after-free on address 0x603000e49a90 at pc 0x7feb7b6ac6a2 bp 0x7ffe83b7c520 sp 0x7ffe83b7bcc8
READ of size 2 at 0x603000e49a90 thread T0
    #0 0x7feb7b6ac6a1 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x776a1)
    #1 0x5599554104ad in luv_spawn /home/vsts/.esy/3/b/opam__s__luv-b92812cd/_build/default/src/c/helpers.c:653
    #2 0x55995540a764 in luv_stub_137_luv_spawn /home/vsts/.esy/3/b/opam__s__luv-b92812cd/_build/default/src/c/c_generated_functions.c:979
    #3 0x5599549d41d8 in camlLuv_c_generated_functions__fun_5876 (/home/vsts/work/1/s/_esy/test/store/b/oni2-39052cbe/default/test/OniUnitTestRunnerCI.exe+0xa751d8)

0x603000e49a90 is located 0 bytes inside of 25-byte region [0x603000e49a90,0x603000e49aa9)
freed by thread T0 here:
    #0 0x7feb7b7137a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)
    #1 0x55995561afad in caml_empty_minor_heap /home/vsts/.esy/3/b/ocaml-4.10.0-e4568572/runtime/minor_gc.c:398

previously allocated by thread T0 here:
    #0 0x7feb7b713d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
    #1 0x55995542ba97 in ctypes_allocate /home/vsts/.esy/3/b/opam__s__ctypes-opam__c__0.15.1-65c3a0a5/src/ctypes/managed_buffer_stubs.c:71
```
(https://dev.azure.com/onivim/oni2/_build/results?buildId=14506&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=71726f8b-ec69-579e-0160-3ebf391f9fa2)

Which seems like the memory is getting shuffled by the GC even before `luv_spawn` is called

2020-12-02 02:37 UTC, bryphe commented
Pinning the strings via `Ctypes.Root` seems to fix the ASAN error (and keep from crashing on Windows).

But I'm not sure this is quite the right fix - I imagine there is a simpler way to fix this. I'm sure a `ctypes` guru would have a better, simpler approach

2020-12-02 18:05 UTC, bryphe commented
In light of that new info - the 'heap use-after-free' from the newly added `strdup`s, it seems my initial hypothesis was incorrect.

In particular, the `strdup` should be a safe operation, if the strings being passed to `luv_spawn` are correct - the worst case would be that we're doing unnecessary work and shuffling bytes around when it is not necessary. However, this tells us that the collection is actually happening _before_ getting to `luv_spawn`.

After spending some time diving through `ctypes`, I found that the `string` view is doing the right thing - allocating an immovable, C block of memory. However, I believe the issue is here: https://github.com/aantron/luv/blob/59a5418145bc6af3570ec5341d108f8df4e4da35/src/process.ml#L82

I don't think that the created `CArray` actually maintains a reference to the string views, at least from what I could see perusing the codebase. It writes to an allocated piece of memory, but doesn't seem to hold the fat-pointer that the `string` view creates. This means that, potentially, the strings could be collected, since from the point of view of the GC, there's nothing holding onto them - so the `CArray` would just have pointer references, but no link to the managed-fat-pointer that the string view has.

In my case, I think what is happening is that we create those CArrays, and then a subsequent allocation (calculating the list length, or populating args), is causing those strings to be freed. It's non-deterministic because it depends on the allocation profile - if not much is allocated, maybe the minor heap collection doesn't get triggered, and this doesn't reproduce... or if there are a lot of allocations, maybe the minor heap grew or a collection happened prior so it doesn't get triggered again.

This means that the fix needs to come earlier - it's not enough to dup them in the C side, but we need to make sure that the GC knows not to clean these up and that we need the references to last the duration of the call.

While my repro has been around the `env` list (which is huge on windows with `esy`...), I believe there is also a race with the `cwd` and `file` arguments. Since we are releasing the runtime prior to calling `uv_spawn`, and the `ocaml_string` view just points to the ocaml-allocated memory, there's a chance that a GC compaction happening between releasing the runtime and calling `uv_spawn` could shuffle those around - so I've also copied those into stable memory for the duration of the call.

2020-12-02 18:11 UTC, bryphe commented
The latest fix addresses the crash on Windows for me, and fixes the ASAN errors :+1:

2021-01-04 14:04 UTC, aantron commented
@bryphe Thanks for your work. I was delaying the review, because I was hoping to combine merging this with upgrading to the next libuv release, and then to release everything together. However, libuv appears to have departed from their former about-monthly release schedule, so I'll review this shortly and do the release once it's in. However, please let me know if you don't need a speedy release, as I will then I will merge the PR, but continue to hold out for libuv before releasing.

2021-01-04 16:25 UTC, bryphe commented
No worries, @aantron ! Thank you for reviewing.

> However, please let me know if you don't need a speedy release, as I will then merge the PR, but continue to hold out for libuv before releasing.

No time pressure on the review or release; I've temporarily picked up the change here: https://github.com/onivim/oni2/blob/5facf4274f231911d10a62d5a97f3f5535a3e5e3/package.json#L220 just to unblock Onivim (the crash was causing the extension host process to fail to start in some cases on Windows)

I'll point back here in the next release, though :+1:

2021-01-14 03:31 UTC, aantron requested changes

2021-01-14 03:31 UTC, aantron commented on src/process.ml
> +  let gc_handles = ref (Some (gc_arg_handles, gc_env_handles, c_cwd, c_path)) in
This method of retaining references will break in multithreaded code. Luv uses another method, which is to refer to a value locally further down in the function by passing it to `Sys.opaque_identity`, like so:

https://github.com/aantron/luv/blob/59a5418145bc6af3570ec5341d108f8df4e4da35/src/stream.ml#L164-L173

In this case, `buffers` and `iovecs` must be retained by the GC across the call to `try_write`.

Can you convert your code to use `Sys.opaque_identity`, and see if that also works for you? You should be able to also undo the changes to `luv_spawn`'s Ctypes "signature."

2021-01-14 03:58 UTC, aantron commented on src/c/luv_c_function_descriptions.ml
> +         ptr char @->
You may also be able to restore some of this "signature," and remove some of the manual conversion code in `process.ml`.

2021-02-15 16:56 UTC, aantron commented on src/process.ml
> +  let gc_handles = ref (Some (gc_arg_handles, gc_env_handles, c_cwd, c_path)) in
Now that I looked at the code in an editor, this is fine &mdash; it's a local ref. I had mistaken it for a global one.

2021-02-15 16:57 UTC, aantron approved these changes

2021-02-15 16:58 UTC, merged

2021-02-15 17:00 UTC, aantron commented
Thanks!